### ISSUE TITLE
使用时必须设置telegram？

### ISSUE THREAD

**Issue by weiai123312** [krau/manyacg#1]
运行时出现以下错误，这是否意味着，我必须设置：telegram
please set at least one admin in config file (telegram.admins)
我并不想使用机器人，我只想当做爬虫来使用...请问该项目能否做到？

**Comment by krau** [comment]
目前主要功能就是bot, 所以必须配置 telegram

**Comment by weiai123312** [comment]
> 目前主要功能就是bot， 所以必须配置 telegram

是否能支持该项目换取特定功能的开发？？

**Comment by krau** [comment]
> > 目前主要功能就是bot， 所以必须配置 telegram
> 
> 是否能支持该项目换取特定功能的开发？？

可以考虑. 你需要什么功能?

**Comment by weiai123312** [comment]
> > > 目前主要功能就是bot， 所以必须配置 telegram
> > 
> > 
> > 是否能支持该项目换取特定功能的开发？？
> 
> 可以考虑. 你需要什么功能?

麻烦把TG的用户名发一下，我私信您

**Comment by krau** [comment]
> > > > 目前主要功能就是bot， 所以必须配置 telegram
> > > 
> > > 
> > > 是否能支持该项目换取特定功能的开发？？
> > 
> > 
> > 可以考虑. 你需要什么功能?
> 
> 麻烦把TG的用户名发一下，我私信您

@KrauInMisanthrope
